import { Badge, Button, Card, Input, Select, Textarea } from "@automagic/ui";

import { providers, skills } from "../../../_data/sandbox";

export default function GenerateMissionPage() {
  const connectedProviders = providers.filter((provider) => provider.status === "connected");

  return (
    <div className="sandbox-page">
      <section className="provider-grid">
        <Card title="Configuration" eyebrow="BYOK">
          <div className="progress-list">
            <Select
              label="Model"
              defaultValue={connectedProviders[0]?.id}
              options={connectedProviders.map((provider) => ({
                value: provider.id,
                label: `${provider.label} · ${provider.model} · key ending ${provider.keySuffix}`,
              }))}
              description="Usage is billed to the trainee's provider account."
            />
            <Select
              label="Skill"
              defaultValue="inbox_calendar"
              options={skills.map((skill) => ({ value: skill.key, label: skill.name }))}
            />
            <Select
              label="Difficulty"
              defaultValue="2"
              options={[
                { value: "1", label: "Easy" },
                { value: "2", label: "Medium" },
                { value: "3", label: "Hard" },
              ]}
            />
            <Select
              label="Simulated tool"
              defaultValue="inbox"
              options={[
                { value: "inbox", label: "Inbox" },
                { value: "crm", label: "CRM" },
                { value: "spreadsheet", label: "Spreadsheet" },
                { value: "calendar", label: "Calendar" },
                { value: "support", label: "Support desk" },
              ]}
            />
            <Input label="Length" defaultValue="25 minutes" />
            <Textarea
              label="Optional twist"
              placeholder="Example: client is in a different timezone and impatient"
            />
            <Button variant="primary" label="Generate mission" />
          </div>
        </Card>

        <Card
          title="Preview"
          eyebrow="Generated by Claude · just now"
          action={<Badge tone="accent">Structured JSON validated</Badge>}
        >
          <article className="mission-card">
            <div className="inline-row">
              <Badge tone="accent">Medium</Badge>
              <Badge tone="info">Inbox and calendar</Badge>
              <Badge tone="success">+120 XP</Badge>
            </div>
            <h3>Triage a 40-email backlog after a week off</h3>
            <p>
              A client returns from holiday to a flooded inbox. Sort, prioritise, draft replies to
              the five urgent threads, and book two callbacks without missing the hidden invoice
              dispute.
            </p>
            <ul className="objective-list">
              {[
                "Label and archive low-priority mail",
                "Draft replies to 5 urgent threads",
                "Book 2 callbacks on the calendar",
                "Flag the invoice dispute to the client",
              ].map((objective) => (
                <li key={objective}>{objective}</li>
              ))}
            </ul>
            <p className="schema-note">
              Generated with the selected BYOK provider. The same provider and model are stored on
              the mission and used later for grading and coach hints.
            </p>
            <div className="inline-row">
              <Button label="Regenerate" />
              <Button href="/missions/m-217" variant="primary" label="Start mission" />
            </div>
          </article>
        </Card>
      </section>
    </div>
  );
}
